# Generated by Django 4.2.16 on 2025-02-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_clientaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientaddress',
            name='postcode',
            field=models.CharField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
    ]
