# Generated by Django 4.2.16 on 2025-02-25 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_clientaddress_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientaddress',
            name='postcode',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
