# Generated by Django 4.2.16 on 2025-03-28 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_alter_clientaddress_postcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('notification_type', models.CharField(choices=[('info', 'اطلاعات'), ('success', 'موفقیت'), ('warning', 'هشدار'), ('danger', 'خطر')], default='info', max_length=20, verbose_name='نوع اعلان')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('related_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='لینک مرتبط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلان\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
