# Generated by Django 4.2.16 on 2025-04-07 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='شماره تلفن')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='تأیید شماره تلفن')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='کد تأیید')),
                ('verification_code_created_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ایجاد کد تأیید')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل\u200cها',
            },
        ),
    ]
