# Generated by Django 4.2.16 on 2025-04-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='profile',
            name='economic_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='کد اقتصادی'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شغل'),
        ),
        migrations.AddField(
            model_name='profile',
            name='legal_info',
            field=models.TextField(blank=True, null=True, verbose_name='اطلاعات حقوقی'),
        ),
        migrations.AddField(
            model_name='profile',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='profile',
            name='refund_method',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='روش بازگرداندن پول'),
        ),
    ]
