# Generated by Django 4.2.16 on 2025-04-12 22:30

import account.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_birth_date_profile_economic_code_profile_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='کد ملی باید دقیقاً 10 رقم باشد', regex='^\\d{10}$'), account.models.validate_national_id], verbose_name='کد ملی'),
        ),
    ]
