# Generated by Django 4.2.16 on 2025-07-22 18:01

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shopApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCategorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم  --  فارسی --  دسته بندی اصلی')),
                ('en_name', models.CharField(max_length=50, unique=True, verbose_name='اسم- --انگلیسی-- دسته بندی اصلی')),
                ('description', models.TextField(verbose_name='توضیحات دسته بندی اصلی')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shopApp.models.upload_BaseCategory_image_path, verbose_name='عکس دسته بندی اصلی')),
            ],
            options={
                'verbose_name': 'دسته بندی  اصلی ',
                'verbose_name_plural': 'دسته بندی های اصلی',
            },
        ),
        migrations.CreateModel(
            name='BaseColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام رنگ')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#FF0000', 'red'), ('#008000', 'green'), ('#0000FF', 'blue')], verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'رنگ پایه',
                'verbose_name_plural': 'رنگ های پایه',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام ---فارسی')),
                ('en_name', models.CharField(max_length=50, unique=True, verbose_name='نام ---انگلیسی')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=shopApp.models.upload_brand_image_path, verbose_name='لوگو برند')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='نام دسته بندی ---فارسی')),
                ('en_name', models.CharField(max_length=20, unique=True, verbose_name='نام دسته بندی ---انگلیسی')),
                ('description', models.TextField(verbose_name='توضیحات دسته بندی')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shopApp.models.upload_cat_image_path, verbose_name='عکس دسته بندی')),
                ('base_catgory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shopApp.basecategorys', verbose_name='دسته بندی اصلی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shopApp.category', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام رنگ')),
                ('hex_code', models.CharField(help_text=' مثال: #FFFFFF', max_length=7, verbose_name='کد هگز رنگ')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shopApp.models.upload_color_image_path, verbose_name='تصویر رنگ')),
                ('base_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='shopApp.basecolor', verbose_name='رنگ پایه')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان اسلاید')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='زیرعنوان اسلاید')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shopApp.models.upload_slider_image_path, verbose_name='تصویر اسلاید')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'اسلایدر صفحه اصلی',
                'verbose_name_plural': 'اسلایدرهای صفحه اصلی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام محصول')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=False, verbose_name='موجود')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان اضافه شدن')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='عکس')),
                ('categories', models.ManyToManyField(to='shopApp.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان بنر')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shopApp.models.upload_banner_image_path, verbose_name='تصویر بنر')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('position', models.CharField(choices=[('top', 'بالای صفحه'), ('middle', 'وسط صفحه'), ('bottom', 'پایین صفحه')], default='middle', max_length=10, verbose_name='موقعیت در صفحه')),
                ('size', models.CharField(choices=[('full', 'تمام عرض'), ('half', 'نیم عرض'), ('third', 'یک سوم')], default='full', max_length=10, verbose_name='اندازه بنر')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنرهای تبلیغاتی',
                'ordering': ['position', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='نام سایت')),
                ('site_url', models.URLField(verbose_name='آدرس سایت')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='لوگوی سایت')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='فاوآیکون سایت')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='اینستاگرام')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='تلگرام')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='توییتر')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینکدین')),
                ('footer_text', models.TextField(verbose_name='متن فوتر')),
                ('about_text', models.TextField(verbose_name='درباره ما')),
                ('seo_keywords', models.TextField(blank=True, null=True, verbose_name='کلمات کلیدی سئو')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='توضیحات سئو')),
                ('shipping_cost', models.PositiveIntegerField(default=0, verbose_name='هزینه ارسال')),
                ('free_shipping_threshold', models.PositiveIntegerField(default=0, verbose_name='حداقل خرید برای ارسال رایگان')),
                ('tax_percentage', models.FloatField(default=9.0, verbose_name='درصد مالیات')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL'), ('4XL', '4XL')], max_length=10, null=True, verbose_name='سایز')),
                ('number_size', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سایز عددی (برای مواردی مثل کفش)')),
                ('size_numrical', models.CharField(max_length=10, verbose_name='سایز عددی نوشتاری')),
                ('category', models.CharField(blank=True, choices=[('clothing', 'لباس'), ('shoes', 'کفش'), ('accessories', 'اکسسوری')], max_length=20, null=True, verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایزها',
                'ordering': ['number_size'],
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان صفحه')),
                ('slug', models.SlugField(unique=True, verbose_name='نامک')),
                ('content', models.TextField(verbose_name='محتوای صفحه')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان سئو')),
                ('seo_keywords', models.TextField(blank=True, null=True, verbose_name='کلمات کلیدی سئو')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='توضیحات سئو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'صفحه استاتیک',
                'verbose_name_plural': 'صفحات استاتیک',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مشخصه')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True)),
                ('data_type', models.CharField(choices=[('int', 'عدد صحیح'), ('decimal', 'عدد اعشاری'), ('str', 'متن'), ('bool', 'بله/خیر')], max_length=20, verbose_name='نوع داده')),
                ('unit', models.CharField(blank=True, max_length=30, null=True, verbose_name='واحد')),
                ('is_main', models.BooleanField(default=False, help_text='مشخصه اصلی برای محصولات است', verbose_name='مشخصه اصلی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_definitions', to='shopApp.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'مشخصه',
                'verbose_name_plural': 'مشخصات',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد')),
                ('weight', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='وزن به گرم')),
                ('is_active_package', models.BooleanField(default=False, verbose_name=' موجود ؟')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.BigIntegerField(verbose_name='قیمت برای این ویژگی ها')),
                ('final_price', models.BigIntegerField(default=0, editable=False, verbose_name='  قیمت نهایی با این ویژگی ها ')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='درصد تخفیف')),
                ('is_active_discount', models.BooleanField(default=False, verbose_name='اعمال تخفیف')),
                ('sold_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فروش')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('brand', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopApp.brand', verbose_name='برند')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopApp.color', verbose_name='رنگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_packages', to='shopApp.product')),
                ('size', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='shopApp.size')),
            ],
            options={
                'verbose_name': ' ویژگی های محصول',
                'verbose_name_plural': ' ویژگی های محصولات',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=shopApp.models.upload_image_path, verbose_name='عکس')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'گالری',
            },
        ),
        migrations.CreateModel(
            name='FeaturedBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.brand', verbose_name='برند')),
            ],
            options={
                'verbose_name': 'برند ویژه',
                'verbose_name_plural': 'برندهای ویژه',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن نظر')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='shopApp.comment', verbose_name='پاسخ به')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(blank=True, to='shopApp.category', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='basecategorys',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='base_categories', to='shopApp.brand', verbose_name='برند های دسته بندی'),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_value', models.IntegerField(blank=True, null=True, verbose_name='مقدار عددی')),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مقدار اعشاری')),
                ('str_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='مقدار متنی')),
                ('bool_value', models.BooleanField(blank=True, null=True, verbose_name='مقدار بله/خیر')),
                ('is_main', models.BooleanField(default=False, help_text='مشخصه اصلی برای محصول است', verbose_name='مشخصه اصلی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_values', to='shopApp.product', verbose_name='محصول')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='shopApp.specification', verbose_name='مشخصه')),
            ],
            options={
                'verbose_name': 'مقدار مشخصه محصول',
                'verbose_name_plural': 'مقادیر مشخصات محصول',
                'unique_together': {('product', 'specification')},
            },
        ),
    ]
