# Generated by Django 4.2.16 on 2024-12-09 11:21

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shopApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCategorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم  --  فارسی --  دسته بندی اصلی')),
                ('en_name', models.CharField(max_length=50, unique=True, verbose_name='اسم- --انگلیسی-- دسته بندی اصلی')),
                ('description', models.TextField(verbose_name='توضیحات دسته بندی اصلی')),
                ('image', models.ImageField(upload_to=shopApp.models.upload_BaseCategory_image_path, verbose_name='عکس دسته بندی اصلی')),
            ],
            options={
                'verbose_name': 'دسته بندی  اصلی ',
                'verbose_name_plural': 'دسته بندی های اصلی',
            },
        ),
        migrations.CreateModel(
            name='BaseColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_code', colorfield.fields.ColorField(blank=True, choices=[('#FFFFFF', 'سفید'), ('#000000', 'مشکی'), ('#FF0000', 'قرمز'), ('#00FF00', 'سبز'), ('#0000FF', 'آبی'), ('#B469FF', 'صورتی'), ('#9400D3', 'بنفش'), ('#964B00', 'قهوای'), ('#808080', 'خاکستری'), ('#fa500', 'نارنجی'), ('#FFFF00', 'زرد')], default=None, image_field=None, max_length=25, null=True, samples=None, verbose_name='کد رنگ')),
                ('color_name', models.CharField(max_length=50, verbose_name='نام رنگ')),
                ('color_image', models.ImageField(upload_to=shopApp.models.upload_color_image_path, verbose_name='تصویر رنگ')),
            ],
            options={
                'verbose_name': 'رنگ پایه',
                'verbose_name_plural': 'رنگ های پایه',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام ---فارسی')),
                ('en_name', models.CharField(max_length=50, unique=True, verbose_name='نام ---انگلیسی')),
                ('logo', models.ImageField(upload_to=shopApp.models.upload_brand_image_path, verbose_name='لوگو برند')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='نام دسته بندی ---فارسی')),
                ('en_name', models.CharField(max_length=20, unique=True, verbose_name='نام دسته بندی ---انگلیسی')),
                ('description', models.TextField(verbose_name='توضیحات دسته بندی')),
                ('image', models.ImageField(upload_to=shopApp.models.upload_cat_image_path, verbose_name='عکس دسته بندی')),
                ('base_catgory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shopApp.basecategorys', verbose_name='دسته بندی اصلی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shopApp.category', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=[('#FFFFFF', 'سفید'), ('#000000', 'مشکی'), ('#FF0000', 'قرمز'), ('#00FF00', 'سبز'), ('#0000FF', 'آبی'), ('#B469FF', 'صورتی'), ('#9400D3', 'بنفش'), ('#964B00', 'قهوای'), ('#808080', 'خاکستری'), ('#fa500', 'نارنجی'), ('#FFFF00', 'زرد')], verbose_name='کد رنگ')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم رنگ')),
                ('en_name', models.CharField(max_length=50, unique=True, verbose_name='اسم رنگ --- انگلیسی')),
                ('color_base', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopApp.basecolor', verbose_name='پایه رنگ')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='نام محصول')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=False, verbose_name='موجود')),
                ('price', models.BigIntegerField(verbose_name='قیمت پایه ')),
                ('final_price', models.BigIntegerField(default=0, editable=False, verbose_name='قیمت نهایی')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='درصد تخفیف')),
                ('is_active_discount', models.BooleanField(default=False, verbose_name='اعمال تخفیف')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان اضافه شدن')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('image', models.ImageField(upload_to='uploads/', verbose_name='عکس')),
                ('categories', models.ManyToManyField(to='shopApp.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('other', 'بدون سایز بندی'), ('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'xl'), ('XXL', 'xxl'), ('3XL', '3xl'), ('kid', 'کودک'), ('baby', 'نوزاد')], default='NO-size', max_length=10, verbose_name='سایز')),
                ('size_numrical', models.CharField(blank=True, choices=[('35', '35'), ('35.5', '35.5'), ('36', '36'), ('36.5', '36.5'), ('37', '37'), ('37.5', '37.5'), ('38', '38'), ('38.5', '38.5'), ('39', '39'), ('39.5', '39.5'), ('40', '40'), ('40.5', '40.5'), ('41', '41'), ('41.5', '41.5'), ('42', '42'), ('42.5', '42.5'), ('43', '43'), ('43.5', '43.5'), ('44', '44'), ('44.5', '44.5'), ('45', '45'), ('45.5', '45.5'), ('46', '46'), ('46.5', '46.5'), ('47', '47'), ('47.5', '47.5'), ('48', '48'), ('48.5', '48.5'), ('49', '49'), ('49.5', '49.5'), ('50', '50')], default='NO-size', max_length=10, verbose_name='سایز عددی')),
            ],
            options={
                'verbose_name': 'سایز',
                'verbose_name_plural': 'سایزها',
            },
        ),
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد')),
                ('weight', models.PositiveIntegerField(blank=True, default=0, verbose_name='وزن به گرم')),
                ('is_active_package', models.BooleanField(default=False, verbose_name=' موجود ؟')),
                ('price', models.BigIntegerField(verbose_name='قیمت برای این ویژگی ها')),
                ('final_price', models.BigIntegerField(default=0, editable=False, verbose_name='  قیمت نهایی با این ویژگی ها ')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='درصد تخفیف')),
                ('is_active_discount', models.BooleanField(default=False, verbose_name='اعمال تخفیف')),
                ('brand', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopApp.brand', verbose_name='برند')),
                ('color', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shopApp.color', verbose_name='رنگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='shopApp.product')),
                ('size', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='shopApp.size')),
            ],
            options={
                'verbose_name': ' ویژگی های محصول',
                'verbose_name_plural': ' ویژگی های محصولات',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shopApp.models.upload_image_path, verbose_name='عکس')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'گالری',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='عنوان نظر')),
                ('comment_txt', models.TextField(verbose_name='توضیحات نظر')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='زمان  ثبت نظر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.product', verbose_name=' محصول مورد نظر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='category',
            field=models.ManyToManyField(blank=True, to='shopApp.category', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='basecategorys',
            name='brand',
            field=models.ManyToManyField(to='shopApp.brand', verbose_name='برند های دسته بندی'),
        ),
    ]
