# Generated by Django 4.2.16 on 2024-12-09 11:31

from django.db import migrations, models
import shopApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecolor',
            name='color_image',
            field=models.ImageField(blank=True, upload_to=shopApp.models.upload_color_image_path, verbose_name='تصویر رنگ'),
        ),
    ]
