# Generated by Django 4.2.16 on 2025-07-22 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpackage',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopApp.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='productpackage',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='وزن به گرم'),
        ),
    ]
