# Generated by Django 4.2.16 on 2025-01-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_alter_basecolor_color_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active_discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
