# Generated by Django 4.2.16 on 2025-01-14 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0003_remove_product_discount_remove_product_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpackage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_main', to='shopApp.product'),
        ),
    ]
