# Generated by Django 4.2.16 on 2025-01-14 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0004_alter_productpackage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpackage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_packages', to='shopApp.product'),
        ),
    ]
