# Generated by Django 4.2.16 on 2025-02-13 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0005_alter_productpackage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpackage',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
