# Generated by Django 4.2.16 on 2025-03-31 21:04

import colorfield.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shopApp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopApp', '0006_productpackage_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان اسلاید')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='زیرعنوان اسلاید')),
                ('image', models.ImageField(upload_to=shopApp.models.upload_slider_image_path, verbose_name='تصویر اسلاید')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'اسلایدر صفحه اصلی',
                'verbose_name_plural': 'اسلایدرهای صفحه اصلی',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان بنر')),
                ('image', models.ImageField(upload_to=shopApp.models.upload_banner_image_path, verbose_name='تصویر بنر')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('position', models.CharField(choices=[('top', 'بالای صفحه'), ('middle', 'وسط صفحه'), ('bottom', 'پایین صفحه')], default='middle', max_length=10, verbose_name='موقعیت در صفحه')),
                ('size', models.CharField(choices=[('full', 'تمام عرض'), ('half', 'نیم عرض'), ('third', 'یک سوم')], default='full', max_length=10, verbose_name='اندازه بنر')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنرهای تبلیغاتی',
                'ordering': ['position', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='نام سایت')),
                ('site_url', models.URLField(verbose_name='آدرس سایت')),
                ('logo', models.ImageField(upload_to='settings/', verbose_name='لوگوی سایت')),
                ('favicon', models.ImageField(upload_to='settings/', verbose_name='فاوآیکون سایت')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='اینستاگرام')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='تلگرام')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='توییتر')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینکدین')),
                ('footer_text', models.TextField(verbose_name='متن فوتر')),
                ('about_text', models.TextField(verbose_name='درباره ما')),
                ('seo_keywords', models.TextField(blank=True, null=True, verbose_name='کلمات کلیدی سئو')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='توضیحات سئو')),
                ('shipping_cost', models.PositiveIntegerField(default=0, verbose_name='هزینه ارسال')),
                ('free_shipping_threshold', models.PositiveIntegerField(default=0, verbose_name='حداقل خرید برای ارسال رایگان')),
                ('tax_percentage', models.FloatField(default=9.0, verbose_name='درصد مالیات')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان صفحه')),
                ('slug', models.SlugField(unique=True, verbose_name='نامک')),
                ('content', models.TextField(verbose_name='محتوای صفحه')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('seo_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان سئو')),
                ('seo_keywords', models.TextField(blank=True, null=True, verbose_name='کلمات کلیدی سئو')),
                ('seo_description', models.TextField(blank=True, null=True, verbose_name='توضیحات سئو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'صفحه استاتیک',
                'verbose_name_plural': 'صفحات استاتیک',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر', 'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['number_size'], 'verbose_name': 'سایز', 'verbose_name_plural': 'سایزها'},
        ),
        migrations.RemoveField(
            model_name='basecategorys',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='basecolor',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='basecolor',
            name='color_image',
        ),
        migrations.RemoveField(
            model_name='basecolor',
            name='color_name',
        ),
        migrations.RemoveField(
            model_name='color',
            name='color',
        ),
        migrations.RemoveField(
            model_name='color',
            name='color_base',
        ),
        migrations.RemoveField(
            model_name='color',
            name='en_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_txt',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='size',
            name='size_numrical',
        ),
        migrations.AddField(
            model_name='basecolor',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#FF0000', 'red'), ('#008000', 'green'), ('#0000FF', 'blue')], verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='basecolor',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام رنگ'),
        ),
        migrations.AddField(
            model_name='color',
            name='base_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='shopApp.basecolor', verbose_name='رنگ پایه'),
        ),
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default='ff5733', help_text=' مثال: #FFFFFF', max_length=7, verbose_name='کد هگز رنگ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='color',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shopApp.models.upload_color_image_path, verbose_name='تصویر رنگ'),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='زمان ثبت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=1, verbose_name='متن نظر'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpackage',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='sold_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد فروش'),
        ),
        migrations.AddField(
            model_name='productpackage',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AddField(
            model_name='size',
            name='category',
            field=models.CharField(blank=True, choices=[('clothing', 'لباس'), ('shoes', 'کفش'), ('accessories', 'اکسسوری')], max_length=20, null=True, verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='size',
            name='custom_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سایز دلخواه'),
        ),
        migrations.AddField(
            model_name='size',
            name='number_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سایز عددی (برای مواردی مثل کفش)'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام رنگ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL'), ('4XL', '4XL')], max_length=10, null=True, verbose_name='سایز'),
        ),
        migrations.CreateModel(
            name='FeaturedBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.brand', verbose_name='برند')),
            ],
            options={
                'verbose_name': 'برند ویژه',
                'verbose_name_plural': 'برندهای ویژه',
                'ordering': ['order'],
            },
        ),
    ]
