# Generated by Django 4.2.16 on 2025-04-02 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0007_homeslider_promotionalbanner_sitesettings_staticpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='shopApp.comment', verbose_name='پاسخ به'),
        ),
    ]
