# Generated by Django 4.2.16 on 2025-04-02 20:10

from django.db import migrations, models
import django.utils.timezone
import shopApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0008_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='custom_size',
        ),
        migrations.AddField(
            model_name='size',
            name='size_numrical',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, verbose_name='سایز عددی نوشتاری'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basecategorys',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shopApp.models.upload_BaseCategory_image_path, verbose_name='عکس دسته بندی اصلی'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=shopApp.models.upload_brand_image_path, verbose_name='لوگو برند'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shopApp.models.upload_cat_image_path, verbose_name='عکس دسته بندی'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shopApp.models.upload_image_path, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shopApp.models.upload_slider_image_path, verbose_name='تصویر اسلاید'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shopApp.models.upload_banner_image_path, verbose_name='تصویر بنر'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='فاوآیکون سایت'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='لوگوی سایت'),
        ),
    ]
