# Generated by Django 4.2.16 on 2025-04-02 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0009_remove_size_custom_size_size_size_numrical_and_more'),
        ('shopApp', 'add_size_numrical'),
    ]

    operations = [
    ]
