# Generated by Django 4.2.16 on 2025-04-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0010_merge_20250403_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='basecategorys',
            name='brands',
            field=models.ManyToManyField(related_name='base_categories', to='shopApp.brand', verbose_name='برند های دسته بندی'),
        ),
    ]
