# Generated by Django 4.2.16 on 2025-04-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0011_basecategorys_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecategorys',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='base_categories', to='shopApp.brand', verbose_name='برند های دسته بندی'),
        ),
    ]
