# Generated by Django 4.2.16 on 2025-07-06 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0012_alter_basecategorys_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مشخصه')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True)),
                ('data_type', models.CharField(choices=[('int', 'عدد صحیح'), ('decimal', 'عدد اعشاری'), ('str', 'متن'), ('bool', 'بله/خیر')], max_length=20, verbose_name='نوع داده')),
                ('unit', models.CharField(blank=True, max_length=30, null=True, verbose_name='واحد')),
                ('is_main', models.BooleanField(default=False, help_text='مشخصه اصلی برای محصولات است', verbose_name='مشخصه اصلی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_definitions', to='shopApp.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'مشخصه',
                'verbose_name_plural': 'مشخصات',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_value', models.IntegerField(blank=True, null=True, verbose_name='مقدار عددی')),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مقدار اعشاری')),
                ('str_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='مقدار متنی')),
                ('bool_value', models.BooleanField(blank=True, null=True, verbose_name='مقدار بله/خیر')),
                ('is_main', models.BooleanField(default=False, help_text='مشخصه اصلی برای محصول است', verbose_name='مشخصه اصلی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_values', to='shopApp.product', verbose_name='محصول')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='shopApp.specification', verbose_name='مشخصه')),
            ],
            options={
                'verbose_name': 'مقدار مشخصه محصول',
                'verbose_name_plural': 'مقادیر مشخصات محصول',
                'unique_together': {('product', 'specification')},
            },
        ),
    ]
