# Generated by Django 4.2.16 on 2025-02-06 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
    ]
