# Generated by Django 4.2.16 on 2025-03-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cartitem_product_cartitem_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('در حال انتظار', 'pending'), ('تأیید شده', 'confirmed'), ('ارسال شده', 'shipped'), ('تحویل داده شده', 'delivered'), ('لغو شده', 'canceled')], default='در حال انتظار', max_length=20),
        ),
    ]
