# Generated by Django 4.2.16 on 2025-03-24 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_clientaddress_postcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0005_alter_cart_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('online', 'پرداخت آنلاین'), ('wallet', 'کیف پول'), ('cod', 'پرداخت در محل')], max_length=50)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('در حال انتظار', 'pending'), ('تأیید شده', 'confirmed'), ('ارسال شده', 'shipped'), ('تحویل داده شده', 'delivered'), ('لغو شده', 'canceled')], default='در حال انتظار', max_length=20)),
                ('shipping_cost', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField()),
                ('discount_code', models.CharField(blank=True, max_length=50, null=True)),
                ('discount_amount', models.PositiveIntegerField(default=0)),
                ('shipping_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.clientaddress')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cart.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
