# Generated by Django 4.2.16 on 2025-03-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='jalali_delivery_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('post', 'پست'), ('tipax', 'تیپاکس'), ('express', 'پیک موتوری')], default='post', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
