# Generated by Django 4.2.16 on 2025-04-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_order_payment_error_order_payment_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('پرداخت شده', 'پرداخت شده'), ('در انتظار پرداخت', 'در انتظار پرداخت'), ('ناموفق', 'ناموفق'), ('لغو شده', 'لغو شده')], default='در انتظار پرداخت', max_length=20, verbose_name='وضعیت پرداخت'),
        ),
    ]
